### ISSUE TITLE
'count' and 'total' not intuitive

### ISSUE THREAD

**Issue by pbienst** [ianxm/emacs-tracker#5]
Perhaps it's just me, but I always need to think a few seconds about whether to use count or total.
How about instead:

total --> sum_values_in_entries
count --> count_entries

Feel free to close and ignore if you don't like this.

**Comment by ianxm** [comment]
I personally use total often and count only rarely, and since total is the default I don't stop to think about it. I don't like the longer names. I would consider swapping 'sum' for 'total' if that would be a great help, but I think I prefer total. total seems less math-y and a more natural way of saying "all of it."

resolving. you can reopen if you think I'm missing something.
